---
- name: Time 동기화
  hosts: datacenters
  roles:
    - rhel-system-roles.timesync

  post_tasks:
    - name: Set timeZone
      timezone:
        name: "{{ host_timezone }}"
      notify: restart chronyd

  handlers:
    - name: restart chronyd
      service:
        name: chronyd
        state: restarted
        